algo=input('Digite algo: ')
print('O tipo primitivo do valor "{}" é '.format(algo), type(algo))
print('{} é um número? '.format(algo), algo.isnumeric())
print('Só tem espaços? ', algo.isspace())
print('{} é alfabético? '.format(algo), algo.isalpha())
print('{} é alfanumérico? '.format(algo), algo.isalnum())
print('Está em maiúsculas? ', algo.isupper())
print('Está em minúsculas? ', algo.islower())
print('Está capitalizada? ', algo.istitle())
